---
name: Test

on:
  pull_request:

jobs:
  test:
    name: Test Compilation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm & install packages
        uses: pnpm/action-setup@v2
        with:
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm

      - name: Fetch data
        run: pnpm run fetch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests (build is okay)
        run: pnpm run build
