name: Test

on:
  pull_request:

jobs:
  test:
    name: Test Compilation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Use Node.js
        uses: actions/setup-node@v2.5.1

      - name: Install packages
        run: npm ci

      - name: Run tests
        run: npm run test
